sqlplus system/System1234

CREATE USER REACT IDENTIFIED BY REACT;
GRANT CONNECT, RESOURCE, DBA TO REACT;
GRANT ALTER SESSION TO REACT;

conn REACT / REACT

show user

DROP TABLE ACCOUNTS CASCADE CONSTRAINT;
CREATE TABLE ACCOUNTS
(
USERID VARCHAR2(20 BYTE) NOT NULL,
USERNAME VARCHAR2(20 BYTE),
USERPASSWORD VARCHAR2(20 BYTE),
USERMAIL VARCHAR2(30 BYTE),
USERPHONE VARCHAR2(20 BYTE),
USERPROFILE VARCHAR2(100 BYTE),
USERFULLADDRESS VARCHAR2(100 BYTE),
USERSUBADDRESS VARCHAR2(100 BYTE),
CONSTRAINT ACCOUNTS_PK PRIMARY KEY(USERID)
) ;


DROP TABLE POST;
CREATE TABLE POST
(
POST_NO NUMBER,
USERID VARCHAR2(20 BYTE),
USERNAME VARCHAR2(20 BYTE),
TITLE VARCHAR2(200 BYTE),
CONTENT LONG,
IMAGE VARCHAR2(200 BYTE),
CONSTRAINT POST_PK PRIMARY KEY(POST_NO),
CONSTRAINT POST_FK FOREIGN KEY(USERID) REFERENCES ACCOUNTS(USERID)
 ) ;

DROP TABLE POST_COMMENT;
CREATE TABLE POST_COMMENT
(
USERID VARCHAR2(20 BYTE) NOT NULL,
POST_NO NUMBER NOT NULL,
GOOD NUMBER(1,0) DEFAULT 0,
STAR NUMBER(2,0) DEFAULT 0,
CONSTRAINT POST_COMMENT_P_FK FOREIGN KEY(POST_NO) REFERENCES POST(POST_NO)
);

COMMIT;