sqlplus system/System1234

CREATE USER REACT IDENTIFIED BY REACT;
GRANT CONNECT, RESOURCE, DBA TO REACT;
GRANT ALTER SESSION TO REACT;

conn REACT / REACT

show user

DROP TABLE ACCOUNTS CASCADE CONSTRAINT;
CREATE TABLE ACCOUNTS 
(
  IDX NUMBER NOT NULL 
, USERID VARCHAR2(20 BYTE) 
, USERNAME VARCHAR2(20 BYTE) 
, USERPASSWORD VARCHAR2(20 BYTE) 
, USERMAIL VARCHAR2(30 BYTE) 
, USERPHONE VARCHAR2(20 BYTE) 
, USERPROFILE VARCHAR2(100 BYTE) 
, USERFULLADDRESS VARCHAR2(100 BYTE) 
, USERSUBADDRESS VARCHAR2(100 BYTE) 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;


--게시판정보
DROP TABLE TB_BOARD CASCADE CONSTRAINT;
CREATE TABLE TB_BOARD(
  NO VARCHAR2(30),             		-- 게시글번호 
  ID VARCHAR2(20),            		-- 아이디 
  TITLE VARCHAR2(100),        		-- 게시글제목 
  CONTENTS VARCHAR2(1000),     		-- 게시글내용 
  DATE DATE DEFAULT SYSDATE,          	-- 게시글작성날짜 
  HITS NUMBER DEFAULT 0,     		-- 조회수  
  GCNT NUMBER(3) DEFAULT 0		-- 좋아요
);

commit;