sqlplus system/System1234

CREATE USER LOGIN IDENTIFIED BY LOGIN;
GRANT CONNECT, RESOURCE, DBA TO LOGIN;
GRANT ALTER SESSION TO LOGIN;

conn LOGIN / LOGIN

show user

DROP TABLE ACCOUNTS ;
CREATE TABLE ACCOUNTS 
(
  IDX NUMBER NOT NULL 
, USERID VARCHAR2(20 BYTE) 
, USERNAME VARCHAR2(20 BYTE) 
, USERPASSWORD VARCHAR2(20 BYTE) 
, USERMAIL VARCHAR2(30 BYTE) 
, USERPHONE VARCHAR2(20 BYTE) 
, USERPROFILE VARCHAR2(100 BYTE) 
, USERFULLADDRESS VARCHAR2(100 BYTE) 
, USERSUBADDRESS VARCHAR2(100 BYTE) 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

commit;