sqlplus system/System1234

CREATE USER BOARD IDENTIFIED BY BOARD;
GRANT CONNECT, RESOURCE, DBA TO BOARD;
GRANT ALTER SESSION TO BOARD;

conn BOARD / BOARD

show user

--------------------------------------------------------
--  DDL for Sequence MEMBER_SEQ
--------------------------------------------------------
   DROP SEQUENCE "DATA"."MEMBER_SEQ";
   CREATE SEQUENCE  "DATA"."MEMBER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence POST_SEQ
--------------------------------------------------------
   DROP SEQUENCE "DATA"."POST_SEQ";
   CREATE SEQUENCE  "DATA"."POST_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------
  DROP TABLE "DATA"."MEMBER";
  CREATE TABLE "DATA"."MEMBER" 
   (	"PK" NUMBER(11,0), 
	"ID" VARCHAR2(100 BYTE), 
	"PASSWORD" VARCHAR2(100 BYTE), 
	"NAME" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table POST
--------------------------------------------------------
  DROP TABLE "DATA"."POST";
  CREATE TABLE "DATA"."POST" 
   (	"PK" NUMBER(11,0), 
	"USER_ID" VARCHAR2(100 BYTE), 
	"USER_NAME" VARCHAR2(100 BYTE), 
	"TITLE" VARCHAR2(200 BYTE), 
	"CONTENT" LONG, 
	"IMAGE" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table POST_COMMENT
--------------------------------------------------------
  DROP TABLE "DATA"."POST_COMMENT";
  CREATE TABLE "DATA"."POST_COMMENT" 
   (	"POST_PK" NUMBER(11,0), 
	"USER_PK" NUMBER(11,0), 
	"GOOD" NUMBER(1,0) DEFAULT 0, 
	"STAR" NUMBER(2,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index POST_PK
--------------------------------------------------------
  DROP INDEX "DATA"."POST_PK"
  CREATE UNIQUE INDEX "DATA"."POST_PK" ON "DATA"."POST" ("PK") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------
  DROP INDEX "DATA"."TABLE1_PK"
  CREATE UNIQUE INDEX "DATA"."TABLE1_PK" ON "DATA"."MEMBER" ("PK") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger MEMBER_TRG
--------------------------------------------------------
  DROP TRIGGER "DATA"."MEMBER_TRG" 
  CREATE OR REPLACE TRIGGER "DATA"."MEMBER_TRG" 
BEFORE INSERT ON MEMBER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.PK IS NULL THEN
      SELECT MEMBER_SEQ.NEXTVAL INTO :NEW.PK FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "DATA"."MEMBER_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger POST_TRG
--------------------------------------------------------
  DROP TRIGGER "DATA"."POST_TRG"
  CREATE OR REPLACE TRIGGER "DATA"."POST_TRG" 
BEFORE INSERT ON POST 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.PK IS NULL THEN
      SELECT POST_SEQ.NEXTVAL INTO :NEW.PK FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "DATA"."POST_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------
  
  ALTER TABLE "DATA"."MEMBER" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("PK")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DATA"."MEMBER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "DATA"."MEMBER" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "DATA"."MEMBER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DATA"."MEMBER" MODIFY ("PK" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table POST_COMMENT
--------------------------------------------------------

  ALTER TABLE "DATA"."POST_COMMENT" MODIFY ("USER_PK" NOT NULL ENABLE);
  ALTER TABLE "DATA"."POST_COMMENT" MODIFY ("POST_PK" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table POST
--------------------------------------------------------

  ALTER TABLE "DATA"."POST" ADD CONSTRAINT "POST_PK" PRIMARY KEY ("PK")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DATA"."POST" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "DATA"."POST" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "DATA"."POST" MODIFY ("PK" NOT NULL ENABLE);

commit;